<?xml version="1.0" encoding="utf-8"?><Database Name="DataSets" Class="IrisDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DataSets.mdf;Integrated Security=True" SettingsObjectName="Kohonen.Data.Properties.Settings" SettingsPropertyName="DataSetsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Iris" Member="Iris">
    <Type Name="Iri">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SepalLength" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SepalWidth" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PetalLength" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PetalWidth" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Species" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>